language: php
dist: xenial
php:
    - 8.2
    - 8.3

before_script:
    - export TZ=Asia/Jakarta
    - date
    - pecl install pcov
    - composer install

script:
    - mkdir -p build/logs
    - composer run test

after_script:
    - php vendor/bin/php-coveralls -v
